# Generated by Django 4.2.10 on 2024-02-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=6)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.CharField(max_length=50, unique=True)),
                ('stu_age', models.IntegerField(default=18)),
                ('stu_gender', models.CharField(max_length=1)),
                ('stu_address', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='query_set_practise.department')),
            ],
            options={
                'ordering': ['stu_name'],
            },
        ),
    ]
