# Generated by Django 4.2.10 on 2024-02-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='stu_id',
            field=models.CharField(max_length=7),
        ),
    ]
