# Generated by Django 4.2.10 on 2024-02-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0002_alter_student_details_stu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='stu_gender',
        ),
    ]
