# Generated by Django 4.2.10 on 2024-02-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0003_remove_student_details_stu_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='query_set_practise.student_details')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_set_practise.studentsubject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
