# Generated by Django 4.2.10 on 2024-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0004_studentsubject_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='marks',
            field=models.IntegerField(default=50),
        ),
    ]
