# Generated by Django 4.2.10 on 2024-02-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0005_studentmarks_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_set_practise.student_details'),
        ),
        migrations.CreateModel(
            name='Studentrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='query_set_practise.student_details')),
            ],
        ),
    ]
