# Generated by Django 4.2.10 on 2024-02-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0006_alter_studentmarks_student_studentrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='query_set_practise.student_details'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='query_set_practise.studentsubject'),
        ),
        migrations.AlterField(
            model_name='studentrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rank', to='query_set_practise.student_details'),
        ),
    ]
