# Generated by Django 4.2.10 on 2024-02-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0007_alter_studentmarks_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrank',
            unique_together={('student_rank', 'created_at')},
        ),
    ]
