# Generated by Django 4.2.10 on 2024-02-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0008_alter_studentrank_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ranks', to='query_set_practise.student_details'),
        ),
    ]
