# Generated by Django 4.2.10 on 2024-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_set_practise', '0009_alter_studentrank_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
